### ISSUE TITLE
Incompatible with AndroidX Test Runner 1.4.0

### ISSUE THREAD

**Issue by zawadz88** [stepstone-tech/AndroidTestXRunner#6]
There's an issue with latest version of AndroidX Test Runner dependency:
```
2021-08-06 11:07:38.797 7094-7114/dev.zawadzki.idlingresourceplayground E/AndroidRuntime: FATAL EXCEPTION: Instr: dev.zawadzki.idlingresourceplayground.MyAndroidJUnitRunner
    Process: dev.zawadzki.idlingresourceplayground, PID: 7094
    de.jodamob.reflect.SuperReflectException: de.jodamob.reflect.SuperReflectException: java.lang.NoSuchFieldException: orchestratorListener
        at de.jodamob.reflect.SuperReflect.field(SuperReflect.java:296)
        at de.jodamob.reflect.SuperReflect.get(SuperReflect.java:275)
        at com.stepstone.xrunner.AndroidJUnitXRunner.onStart(AndroidJUnitXRunner.kt:64)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
     Caused by: de.jodamob.reflect.SuperReflectException: java.lang.NoSuchFieldException: orchestratorListener
        at de.jodamob.reflect.SuperReflect.field0(SuperReflect.java:320)
        at de.jodamob.reflect.SuperReflect.field(SuperReflect.java:292)
        at de.jodamob.reflect.SuperReflect.get(SuperReflect.java:275) 
        at com.stepstone.xrunner.AndroidJUnitXRunner.onStart(AndroidJUnitXRunner.kt:64) 
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837) 
     Caused by: java.lang.NoSuchFieldException: orchestratorListener
        at java.lang.Class.getField(Class.java:1048)
        at de.jodamob.reflect.SuperReflect.field0(SuperReflect.java:305)
        at de.jodamob.reflect.SuperReflect.field(SuperReflect.java:292) 
        at de.jodamob.reflect.SuperReflect.get(SuperReflect.java:275) 
        at com.stepstone.xrunner.AndroidJUnitXRunner.onStart(AndroidJUnitXRunner.kt:64) 
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837) 
```

Apparently, the internals of `AndroidJUnitRunner` have changed and the reflection we used no longer works.

**Comment by zawadz88** [comment]
I have a fix in a forked repo: https://github.com/zawadz88/AndroidTestXRunner-1/tree/bugfix/runner_1_4_0_compatibility

There's some more testing and TODOs to be done though as apparently there's something called Orchestrator V2, but I was not able to find out how run it locally with it enabled yet.

Also, with JCenter support ended we'd need to publish to Maven Central probably, but I don't have access to do it 😉 
FYI @fabiozo

**Comment by RobertZagorski** [comment]
Merged the commit. As I have already got the permissions to upload artifacts under com.stepstone group ID in Maven Central, I'll prepare another PR with the new upload scripts.

**Comment by zawadz88** [comment]
Thanks @RobertZagorski!

**Comment by RobertZagorski** [comment]
Along with #9 I think this issue can be closed. New version is published.
